name: Code Quality Checks

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 vulture isort

    - name: Check code formatting with Black
      run: |
        black --check --config .black.toml .
      continue-on-error: false

    - name: Run Flake8 linting
      run: |
        flake8 . --config=.flake8
      continue-on-error: true

    - name: Check for dead code with Vulture
      run: |
        vulture . --config=.vulture.toml
      continue-on-error: true

    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
      continue-on-error: true

    - name: Code quality summary
      if: always()
      run: |
        echo "✅ Code quality checks completed"
        echo "Note: Black formatting is required. Other checks are informational."
